services:
  # Servicio web principal
  - type: web
    name: sistema-citas-whatsapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: citas-db
          property: connectionString
      - key: WHATSAPP_API_URL
        value: https://graph.facebook.com/v19.0/TU_NUMERO_WHATSAPP/messages
      - key: WHATSAPP_TOKEN
        value: TU_TOKEN_WHATSAPP

  # Base de datos PostgreSQL (compatible con Entity Framework)
  - type: pgsql
    name: citas-db
    databaseName: citasdb
    user: citasuser
    plan: free
