services:
  # Servicio web principal
  - type: web
    name: sistema-citas-whatsapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:10000
      - key: PORT
        value: 10000
      - key: WHATSAPP_API_URL
        value: https://graph.facebook.com/v19.0/TU_NUMERO_WHATSAPP/messages
      - key: WHATSAPP_TOKEN
        value: TU_TOKEN_WHATSAPP
      - key: DATABASE_URL
        value: "Server=localhost;Database=CitasDb;Trusted_Connection=True;TrustServerCertificate=True;"
