// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using citas.Data;

#nullable disable

namespace citas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251011080000_AddTitleToAppointments")]
    partial class AddTitleToAppointments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Este archivo es generado automáticamente por EF Core
            // Solo necesitamos que exista para que la migración funcione
        }
    }
}
